### ISSUE TITLE
merge london-biohackers-members google group with hello@ address

### ISSUE THREAD

**Issue by ilevantis** [london-biohackers/biohackspace-general#21]
Would be good to have one fewer lists of people to manage. Make it so incoming hello@ emails go to the london-biohackers-members group.

A reply (reply all) to an incoming hello@ email should be posted in the group as well as being sent to the original mailer.

**Comment by tolland** [comment]
I don't think this is really an issue, more of a preference. In the current scenario, list members can unsubscribe from the hello@ list if they think its spammy or irrelevant, unfortunately aliasing the members list to the hello list removes the subscribers ability to unsubscribe from hello without also unsubscribing from members-

Also members- is on the googlegroups.com domain, and hello is on the biohackspace.org accounts, so I'd be inclined to leave it as it is, unless there is a major benefit in merging them. Personally I am happy to add/remove users, and the other directors are mangers/owners so there shouldn't be an admin bottleneck.

**Comment by ilevantis** [comment]
Is there a reasonable way in which members of 'members-' might be able to add or remove themselves from 'hello'? if not, then having numerous admins is fine I suppose.

**Comment by ilevantis** [comment]
cc: @nfd

**Comment by nfd** [comment]
While I understand @tolland's point about the technical problems, I don't think we should allow members to unsubscribe from hello@. I think of it as analogical to the Hackspace mailing list, which is mostly about posts from members but sometimes includes posts from nonmembers wanting to find out more (or to use the hackspace for their project). If you're interested in the biohackspace enough to join the members list, you should be willing to take on the responsibility to communicate with new and prospective members. It's part of being a member of the community. If you really want to be a part of this volunteer-run and nonprofit organisation but don't want to talk to people about it, then you can create your own private mail filter on hello@.

**Comment by ilevantis** [comment]
Having asked around a bunch of members at last week's iGEM meeting I think I'm inclined to agree fully with @nfd , as did everyone else present. The general opinion was that being a paying member should give you the right to respond to the sorts of emails we get to hello@. Everyone (including non-IT background people) also said they'd be happy to deal with filtering it themselves if necessary.

**Comment by sthompsonxyz** [comment]
merge it

**Comment by tolland** [comment]
So I've since updated and synchronized the members list and the hello@ list, and everyone who is on the -member list is also on the hello@ mailing list. Unfortunately groups cannot be added to other groups, so it's a matter of updating both lists when adding/removing members;
![image from google groups](https://dl.dropboxusercontent.com/u/4171924/Screenshot-080615-185333.png)

**Comment by tolland** [comment]
I am going to mark this as closed...? we can re open if there is a better way to implement this.

**Comment by nfd** [comment]
I guess ideally hello@ would be an alias for l-b-m@? I guess this doesn't work at the moment because l-b-m doesn't allow posts from nonmembers? But since we are effectively allowing posts from nonmembers by having the same membership list on hello@, which allows posts from everybody, then we may as well just allow posts from nonmembers to l-b-m@ and turn hello@ into an alias.

It's late. Am I still making sense?

**Comment by ilevantis** [comment]
I see there is a difference between groups which are not apart of an organisation and those which are. Currently hello@ is part of the limepepper.co.uk organisation and -members is not. Is this important? Should we just get rid of -members and make that an alias of hello@ ?

Whatever we end up with its important that external emails go through a spam filter.

**Comment by tolland** [comment]
One of the things I would like to do is make a https://portal.biohackspace.org for members, and have a bunch of pages for things like equipment status, scheduling for equipment, stock levels for consumables, and a bunch of data dashboards for incubator, fridge, freezer, temps, CO2 levels etc. I would also like to send out notifications if members selected to receive them. (like nagios...for biolab etc)

I think it would be cool to have a page where members can set whether they are notified of things, such as hello@ london-biohackers-members@ and possibly other lists like equipment outage notifications, or events.. So my preference is to keep hello@ and -members separate, simply because the members would be able to set their notification/list membership themselves.

I also think that having separate identities for the replies, hello@biohackspace.org and members@biohackspace.org is preferable, also because there are people on the hello list who do not seem to strictly be members... But I think their contributions justify them seeing those messages.

> Currently hello@ is part of the limepepper.co.uk organisation

I think we should setup another google groups organization for LBL Ltd, and move the lists there. It seems to be free for just managing groups, and IMO its better to keep things separate if it doesn't generate a load of admin.

I'd like to start a portal.biohackspace.org that allows management of some of this stuff, clearly at some point we should start that project. Maybe we should start another thread about whether that is worth the effort and what everyone wants out of it.
